### ISSUE TITLE
REPL

### ISSUE THREAD

**Issue by LightAndLight** [LightAndLight/ipso#170]
Start a REPL when `ipso` is called with no arguments.

Implement the REPL as a library so it can be controlled programmatically. This library has a request-response structure.

Implement the terminal component of the REPL in `ipso-cli`.

## Tasks

* [x] #171
* [x] Integrate REPL into `ipso-cli`
* [x] Pretty print errors
* [x] Rename `ToString` to `Debug`
* [x] Document `Debug`
