### ISSUE TITLE
Make Nix cache public

### ISSUE THREAD

**Issue by LightAndLight** [LightAndLight/ipso#270]
I use Cloudflare R2 storage for my Nix cache, and buckets now have a public access mode: https://developers.cloudflare.com/r2/data-access/public-buckets/.

## Tasks

* [ ] Set up public R2 access with custom domain: `cache.ipso.dev`
* [ ] Document cache domain and public key
* [ ] Add private key to password manager
* [ ] Make sure only public reads are enabled
* [ ] Test public cache locally
