### ISSUE TITLE
`string.split` should take a `String` separator

### ISSUE THREAD

**Issue by LightAndLight** [LightAndLight/ipso#277]
Currently `string.split : Char -> String -> Array String`, but it should be `string.split : String -> String -> Array String`.

Combined with #272,  `string.join` becomes an inverse of `string.split`:

```
string.join sep (string.split sep x) == x
```

We can also create `string.splitc : Char -> String -> Array String` for the single-character case.

## Tasks

* [x] Rename `string.split` to `string.splitc` - #278
* [x] Add `string.split : String -> String -> Array String` - #278
* [x] Update documentation - https://github.com/LightAndLight/ipso/pull/279
